# Generated by Django 3.0.6 on 2020-05-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('u_id', models.CharField(max_length=32)),
                ('m_id', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('m_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=40)),
                ('rate', models.IntegerField(max_length=11)),
                ('director', models.CharField(max_length=50, null=True)),
                ('screenwriter', models.CharField(max_length=50, null=True)),
                ('actor', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(max_length=20, null=True)),
                ('language', models.CharField(max_length=20, null=True)),
                ('length', models.IntegerField(max_length=11, null=True)),
                ('imgurl', models.CharField(max_length=100, null=True)),
                ('star', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('u_id', models.CharField(max_length=32)),
                ('m_id', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50, null=True)),
                ('rate', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendMovie',
            fields=[
                ('m_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('recommend_movie_id', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('u_passwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
