# Generated by Django 3.0.6 on 2020-06-02 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='rating',
        ),
        migrations.AlterModelTable(
            name='recommendmovie',
            table='recommend_movie',
        ),
    ]
